Update readme.md
micromata/awesome-javascript-learning pull request #86
Opened 2023-05-26 07:16 UTC by alishasingh1611

---- 

By submitting this pull request, I promise that:

- [x] I have read the [contribution guidelines](https://github.com/micromata/awesome-javascript-learning/blob/master/.github/contributing.md) thoroughly.
- [x] I ensure my submission follows each and every point.

2023-05-26 12:57 UTC, andrzejsydor commented on readme.md
> +- [Best Free Javascript Course](https://www.interviewbit.com/blog/top-free-javascript-courses-to-learn-online/) - Explore the best free online JavaScript courses for comprehensive learning.
```suggestion
- [Top Free Javascript Course](https://www.interviewbit.com/blog/top-free-javascript-courses-to-learn-online/) - Explore the best free online JavaScript courses for comprehensive learning.
```

2023-06-15 06:08 UTC, andrzejsydor requested changes

2023-06-15 06:08 UTC, andrzejsydor commented on readme.md
> +- [Top Free Javascript Course](https://www.interviewbit.com/blog/top-free-javascript-courses-to-learn-online/) - Explore the best free online JavaScript courses for comprehensive learning.
```suggestion
- [Top Free Javascript Course](https://www.interviewbit.com/blog/top-free-javascript-courses-to-learn-online/) - Explore the top free online JavaScript courses for comprehensive learning.
```

2023-07-02 13:35 UTC, mischah commented
Thanks for the PR ❤️ 

Sorry to say that I have to decline this one.

We do not accept links to collections of resources, only links to individual resources. And , of course, only the finest ones.

Reason: Potential learners should spend their time learning, not clicking through from one list of links to the next. More specifically: The links on this list should be a destination for people who want to learn things, not another stop along the way to find a good learning resource.

I would be happy to accept if you provide one of following PRs:

1. The most awesome resource out of the links of your initial resource
2. An addition to the [contribution guidelines](https://github.com/micromata/awesome-javascript-learning/blob/master/.github/contributing.md) to make this clear: 
 > We do not accept links to collections of resources, only links to individual resources. And , of course, only the finest ones.
 > 
 > Reason: Potential learners should spend their time learning, not clicking through from one list of links to the next. More specifically: The links on this list should be a destination for people who want to learn things, not another stop along the way to find a good learning resource.

Cheers, Michael :octocat:

2023-07-02 13:35 UTC, closed without merging